# Generated by Django 5.0.3 on 2024-03-08 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Correo electronico')),
                ('password', models.CharField(max_length=150, verbose_name='Contrasea')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'User',
                'ordering': ['id'],
            },
        ),
    ]
